apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: tools
spec:
  encryptedData:
    DB_PASSWORD: AgAOLsiPwFD2bLPIgbs7Jy3rehWMKpQAVwWF9RnHY0FadhHaqvWdBk1QtftCU8eyhzzN7xhRLPbtP3KxVNVjBlZzMTGTs6c45D+J3gbdT3EPgxqA3fvv8SkIwZ/crbfU4dAdcnbD4UG3ff0glxfLI9PmRaZApIA5gAzVySpYTrVEwn7d6n3YzxlvssnzUwDVFizGPjmNSBYOW05lPN0qc5fXTZLCsVtLZde0GrKhqWhj15A0GQFoebViwRuXVOX3TKq4bIbS/iG8oWVbvjiV03xYKTcGCaXC5ASPWysHd3j2KdEMbHIXUWHJf/MSWSR+TlwHc5qn4nkqS8sVycM295KluzxJYHYDqAKLjYmfBTcR2IGq1gBhU6RKQVX9bCpKOuY9Mm2xSJfJFrr/RLZew+6A+H9brjQMV2ewqXNOxhJ1RKuZyoaXF8AXS5VIy6x2tv7PuSGrGzLdSUuoZRLZ/LNMGTHZWtwRU53zmDmh3FC9/w1uvG/rE/+Y6JfG201N/HyZTXtskGCpoO1++xSxudgIJvpNI+89j4XnGaBdfJWGT4CDx7qLo53HeWv6xU4o1QZgOPtB9pjTuCzwwIeJysmT4KAsR3T/5TZVbRlXnk4RE7u2hzELCW853gf0vhxvk7TwVq+tAirWCX27hklLg7hyb/DxTUT3SIHh+oBz+3crDV7v2o1zf3/9Mt5LaEC45MniF5UTF+CTCw==
    DB_USER: AgCBqqaHa73rIBHhGhde/1cuKq7HXMdSCKxRoescwm2cpywhFFV0B7PPSbHkgkQ1V1YRkthmfSWIP9qe8z9j6VgolD5+zKpDnVjApVsHRxwDiZ9dJOUHOsdWFQ9pcBGA8Lq5oVWUHOjiXOTOsXHTnhRoO312zXgVsZ8O6n4qXeVsGJmnkQjARQxJX3ss1N9WMVKp0nxZ+PdpSae7WiRI0p2B6w5mHgANlvaphRQ9c7is0O7zte/6VD+z4xSfGySJAzsfOlZeoDkrAbspnj//pMm2tq4x2raPvKBjwL6td3NoAycZFjENE5EN7YYfP8Ivw/cEWibZ+3ZjyiSad0yScmz/f+bxnZbd0R+dXZupN453B5tv3kpM8Nyb50rbc4SDAO4ABYyT5sQKyDN+AzEKmKwI+BTPUq8Tmd+bpvfx12qsgyq9d7brmNErDwS2tH6HV5D9+VEs/GouWks43/sFltCELRFGqlnFZmc2H5uiKIzilhtcjV8DY5K9OIVhsLYJKzFQem32YKwVEFSIo5+S64PQLYInPghoI9PctJx/gLEW+7xc2P+GQImsOTB7GcDbkaS57B91F2yUf2RGA+wc14i5jdk7odtRvNV0A/9YZO77R0gr6OBKXDZMucMhVzOSoGuGH0rBIApPWv9dFOtUHLgeKEWZceLmmv0FNjkUKm4dyygwfjWO8E55aUNUefd5NH4VLcTMEO3SUw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: tools
    type: Opaque

