apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: tools
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgA6wcz2aJSf7GidoGsbVXcqJcN4JmeCev4ba+Kjyvlgd4UCmvwweaVfDApC4aqnOmWo/2zAvSVfp0yCCVlxdIv8Oi3T1rZJcS3hPXEZD1CPNBmcK+X1k/Qs4BTmkHxca7MlOsrEQtNv/WNqFru4F6CKNuC6T9+RGCxUTPCpvhz0xkHBWHpWkzaK85w05WCQ+luXuukd0DwY6utOO3+MLK15xCSsIrbtizpUDktqdM6xtjDEg4mB9MT+dbuQlaQNnL2rskZeZl4wKBvnZXz5GwBGOSGNOh5+CTZo3V/6JHsjvfGzsydXj54P2qoQrsW24ygjrIgxgApy5YylDecMFOltizAwRCwNwYtm2UURovrU5lZBv+a91pFOWuQBC7VBP5+SNRuNuvWydr4VcCnL6X/sD80hrCnYtdy0uAyhJ0pLz9l2MDY25v3gCyVn0dzQubu7kDAbXyqSKn0hoU4WTBtu64QvVJRmAUEdsyZkxsr+9yNoOOAgEtpNovHdpZ/aNUAzx4tvtoIhwXgmnaYz0q/D3Ft7SC2DfcLmMw7pvGvjCHFLp9avcWNU9zJ9Vy0V8UVyYcR3wuFmhELcQFLBMuAaHXrk9SrVKSmlbCKVPeKEucXVT6SXr9VFw3q8LebSZeX0RxvXhxRWTpp13hqOPnrUf4pmrgCh5+IMVg9baw+ttCp0vNgQ8G4T8nWoICDUwhkVfhzpD11HOw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: tools
    type: Opaque

